// Data to fill the form
// const personalData = {
//   Lastname: "ali",
//   Firstname: "ali",
//   DateOfBirth: "08/10/1992",
//   TraveldocumentNumber: "A44415512",
//   Sex: "Female",
//   Street: "alfath st",
//   Postcode: "34532",
//   City: "Cairo",
//   Country: "EGYPT",
//   Telephone: "+201013134133",
//   Email: "mahmoudfathy557@gmail.com",
//   LastnameAtBirth: "Mahmoud",
//   NationalityAtBirth: "EGYPT",
//   CountryOfBirth: "EGYPT",
//   PlaceOfBirth: "Cairo",
//   NationalityForApplication: "EGYPT",
//   TraveldocumentDateOfIssue: "11/09/2024",
//   TraveldocumentValidUntil: "11/08/2031",
//   TraveldocumentIssuingAuthority: "EGYPT",
// };

const personalData = {
  Lastname: "Elshourbagy",
  Firstname: "Mahmoud",
  DateOfBirth: "08/10/1996",
  TraveldocumentNumber: "A32221108",
  Sex: "Male",
  Street: "alfath st",
  Postcode: "35738",
  City: "alainbilawin",
  Country: "EGYPT",
  Telephone: "+201022014166",
  Email: "mahmoudfathy2424@gmail.com",
  LastnameAtBirth: "Mahmoud",
  NationalityAtBirth: "EGYPT",
  CountryOfBirth: "IRAQ",
  PlaceOfBirth: "Baghdad",
  NationalityForApplication: "EGYPT",
  TraveldocumentDateOfIssue: "11/22/2022",
  TraveldocumentValidUntil: "11/21/2029",
  TraveldocumentIssuingAuthority: "EGYPT",
};
module.exports = { personalData };
